gui:
  showBottomLine: true
  nerdFontsVersion: "3"
  showFileIcons: true
  showRandomTip: false
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
disableStartupPopups: false
notARepository: 'skip'
keybinding:
  universal:
    extrasMenu: '@'
    increaseContextInDiffView: '}'
    decreaseContextInDiffView: '{'
  commits:
    moveDownCommit: ''
    moveUpCommit: ''
os:
  editPreset: 'nvim'
